name: Build and Deploy Dockerized PHP App to Elastic Beanstalk

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 215896857075.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t php-app .

      - name: Tag image
        run: |
          docker tag php-app:latest 215896857075.dkr.ecr.us-east-1.amazonaws.com/php-app:latest

      - name: Push image to ECR
        run: |
          docker push 215896857075.dkr.ecr.us-east-1.amazonaws.com/php-app:latest

      - name: Create Dockerrun file zip
        run: |
          zip -r deploy.zip Dockerrun.aws.json

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "phpapp"
          environment_name: "phpapp-env"
          region: "us-east-1"
          version_label: ${{ github.run_id }}
          deployment_package: deploy.zip
